services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\ConfigElementTypeBundle\ConfigElementType\Concrete\:
    resource: '../../ConfigElementType/Concrete/*'
    tags: ['huh.reader.config_element_type', 'huh.list.config_element_type']